### ISSUE TITLE
Error Installing Zen Daemon - Linux (Solus 4.0 - Budgie)

### ISSUE THREAD

**Issue by treepi3** [ZencashOfficial/Sphere_by_Horizen#8]
![image](https://user-images.githubusercontent.com/13264659/57502261-90c2b200-72b0-11e9-9f25-1d13336bd85d.png)

I noticed someone posted about this issue with Windows. However, I'm experiencing it in Linux as well with the latest release of the Sphere wallet.

Is there a fix for this? Also, if someone could point me to where the log files would be, I can paste my log in here to see if that helps identify the issue.

Is there a command I can run from the terminal to install the daemon and download the chain state?

**Comment by vherus** [comment]
Hi @treepi3 

Thanks for the report! We're aware that the zend installation & blockchain sync process can be a little tough to deal with in some situations. This is a super important issue to us, it shouldn't be as difficult as it currently is to sync up the wallets node. In figuring out a solution we are taking every care to ensure we fix this with a high degree of Horizen polish, with the end goal being a swifter, easy to use installation & sync process.

Please bare with us as we tackle issues like this during beta phase of the software, and thank you for your support.

**Comment by Sto1cNate** [comment]
Hey @treepi3

Have a look at the latest release of Sphere by Horizen.

https://github.com/ZencashOfficial/Sphere_by_Horizen/releases/latest

1.1.1-beta should solve the failure.

**Comment by Sto1cNate** [comment]
@treepi3 
You could try removing both of the aforementioned linux directories and then after upgrading Sphere by Horizen to 1.1.1-beta, relaunch it into full mode. It should then do a fresh install of zend and start re-downloading the proving keys.

To remove those directories, open up a terminal and enter the following:
`rm -rd ~/.horizen/zend`
`rm -rd ~/.zcash-params`

You can then upgrade Sphere to 1.1.1-beta and login and switch into full mode.

**Comment by uanl979** [comment]
Will be closing this issue since this is not a supported operating system.

Supported Operating Systems

> For beta launch, we are currently only supporting 64 bit x86 CPUs. 32 bit and ARM64 support may be considered in future releases.
> 
>     Windows 10 64 bit
> 
>     macOS Sierra and above 64 bit
> 
>     Ubuntu 18.04.1 LTS 64 bit
> 
>     Linux Mint 19 Tara 64 bit
> 
>     Debian 9 64 bit
